name: flutty_test
description: "Testing utilities, helpers and matchers for Flutty packages."
version: 0.1.0
homepage: https://github.com/Flutty-Lab/flutty_test
repository: https://github.com/Flutty-Lab/flutty_test
issue_tracker: https://github.com/Flutty-Lab/flutty_test/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
